# Generated by Django 3.0.7 on 2020-06-15 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0004_auto_20200615_0006'),
        ('user', '0008_auto_20200613_0824'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='MyUser',
        ),
        migrations.AlterModelOptions(
            name='myuser',
            options={},
        ),
    ]
