# Generated by Django 3.0.7 on 2020-06-27 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
