# Generated by Django 3.0.7 on 2020-06-27 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='phone',
            new_name='phoneModel',
        ),
    ]
