# Generated by Django 3.0.7 on 2020-06-27 13:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_phonemodel_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonemodel',
            name='users',
        ),
        migrations.AddField(
            model_name='phonemodel',
            name='users',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
