# Generated by Django 3.0.7 on 2020-06-27 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_auto_20200627_0654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonemodel',
            name='users',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='phone_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.phoneModel'),
        ),
    ]
