# Generated by Django 3.0.7 on 2020-07-03 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_auto_20200627_0702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='phone_no',
        ),
        migrations.DeleteModel(
            name='phoneModel',
        ),
    ]
